### ISSUE TITLE
Window border is light when using dark theme and dark mode is on

### ISSUE THREAD

**Issue by sigmondkukla** [rdbende/Sun-Valley-ttk-examples#1]
I'm having an issue with the Sun Valley dark theme in that even with dark mode on and the theme set to dark, the window border is still light theme. Is this simply an issue with the Windows window manager, or can it be fixed with the theme?
![image](https://user-images.githubusercontent.com/50522829/128728651-d56cf50f-251c-4cef-b62b-a00ae83fc411.png)

**Comment by rdbende** [comment]
Unfortunately you can't control the color and look of the window border at all with tkinter. This is handled by the window manager.

**Comment by Rulerofzeworld** [comment]
In the screenshot at https://github.com/rdbende/Sun-Valley-ttk-examples/blob/master/Calculator/Screenshot.png, the window seems to have the desired effect. How did you achieve it?

![image](https://user-images.githubusercontent.com/43553166/131514514-f5085729-de69-4702-9b81-371380ecbcb5.png)

**Comment by rdbende** [comment]
I went into my Plasma system settings and switched the aurorae theme to a Windows 11 looking one.

**Comment by Rulerofzeworld** [comment]
Ah right. Would it be possible to implement the top bar by hiding the default one & adding a separate frame with three buttons anchored top right?
I assume the same could be done for the edges of the window, albeit slightly more challenging to code, by adding a frame on each side and one on each corner for the bezels.

**Comment by rdbende** [comment]
Yes, you could make your own title bar, but with it you lose the taskbar icon and the ability to minimize the window, so :(

**Comment by Rulerofzeworld** [comment]
I believe tkinter has a command for that, which you can just assign to a button.
If I remember correctly, it's `root.state('zoomed')` and `root.attributes('-fullscreen', True)`

**Comment by rdbende** [comment]
I mean iconifying, so when you hide the window to the taskbar, Tk will raise an error, when you try to iconify the window, with `overrideredirect` is set to True.

**Comment by Rulerofzeworld** [comment]
Ah I see. Could we set `overrideredirect` to `False` the instant after the button is pressed, before the window is iconified?

**Comment by rdbende** [comment]
I think it could be possible, however it has problems on Linux, and I can't get it to work. I remember I managed to do this once on Windows.
But then... you will have problems by restoring the `overrideredirect`. Since you can't really capture the deiconification event, it's pretty much impossible. I'll try to find a way, to know when the window is deiconified.

**Comment by Rulerofzeworld** [comment]
This might be of interest: [Tkinter - Run function on minimise/unminimise](https://stackoverflow.com/questions/66304453/how-to-check-if-application-has-been-minimized-or-maximized-by-the-user-in-tkint)

Let me know how it goes, it's a feature I'd be really interested in!

**Comment by sigmondkukla** [comment]
@Rulerofzeworld Thanks for bringing this up! Currently, I'm researching this option and will let you know if I make any progress.

**Comment by rdbende** [comment]
So I found the best tutorial, on how to make custom titlebars [here it is](https://www.youtube.com/watch?v=axMG3fkIhO4).
And yeah, you'll need to put a dummy small window behind the real one and group it with the `group` method, so the taskbar icon will be always visible. And you also need to move that window with the real one.

You can bind the window to the [`<<ThemeChanged>>`](https://www.tcl.tk/man/tcl/TkCmd/event.html#M48) event, and use a `style.lookup` to get the actual window background color.

Rounding the corners of the widow is far easier, at least on Windows and Mac. Just put a rounded rectangle image with transparent background as a background image, and use the `window.attributes("-transparentcolor, "some color")` on Windows, or the `window.config(background="systemTransparentColor")`

**Comment by Rulerofzeworld** [comment]
@rdbende Would it be possible for you to make this as a downloadable github repository?
Being able to simply import this and assign it to a project would be incredible!

Something like:
```python
from tkinter import *
from betterTitlebar import Titlebar

root = tk.Tk()

#Titlebar from your library
bar = Titlebar(root, theme="dark", minimise=True, maximise=False, close=True)
bar.pack()

#Frame for the user's main GUI
mainFrame = Frame(root)
mainFrame.pack()

root.mainloop()
```

**Comment by sigmondkukla** [comment]
> @rdbende Would it be possible for you to make this as a downloadable github repository?
> Being able to simply import this and assign it to a project would be incredible!
> 
> Something like:
> 
> ```python
> from tkinter import *
> from betterTitlebar import Titlebar
> 
> root = tk.Tk()
> 
> #Titlebar from your library
> bar = Titlebar(root, theme="dark", minimise=True, maximise=False, close=True)
> bar.pack()
> 
> #Frame for the user's main GUI
> mainFrame = Frame(root)
> mainFrame.pack()
> 
> root.mainloop()
> ```

Working on something like this right now. Current progress:
![image](https://user-images.githubusercontent.com/50522829/132140723-9921c299-66c6-4028-8d81-b52a29de4a07.png)
Works in light and dark theme. I'll add a pull request to the main repo with the additional Close button style.

**Comment by rdbende** [comment]
Thanks! It looks really nice!

PicoPlanet Developing ***@***.***> ezt írta (időpont: 2021.
szept. 5., V, 22:36):

**Comment by sigmondkukla** [comment]
Published a repository that has some basic functionality: https://github.com/PicoPlanetDev/Sun-Valley-titlebar
Light and dark theme works, and as far as I cant tell, so do all of the buttons. Not entirely sure what will happen if you disable any of the buttons, but I added that into the code. Titlebar syntax is as follows:
```
from sunValleyTitlebar import Titlebar

# Create your root window with minsize theme
# ...
# etc

root.overrideredirect(True)
icon = tk.PhotoImage(file='feather.gif')

big_frame = ttk.Frame(root)

titlebar = Titlebar(root, big_frame, icon, tk_title, True, True, True, 400, 400)

big_frame.pack(fill="both", expand=True)

# Put whatever you want in the big_frame

root.mainloop()
```
@rdbende Please let me know if you would prefer that I do not include the theme in my repository. At this time, I have created a pull request on your main Sun-Valley-ttk-theme to include a Close button style (used for my close button). I'm not exactly a pro when it comes to contributing to repos so any necessary guidance will be welcomed wholeheartedly.

On my TODO list for this (as in, does anyone want to help lol):
- Create a rounded corner background (radius 8px according to https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/geometry)
- Add a custom Menubar function (because I believe that using a built in menubar at this point would make it go above the titlebar or not appear at all)
- Other ideas?

**Comment by sigmondkukla** [comment]
Current progress on this:
![TitlebarDemo](https://user-images.githubusercontent.com/50522829/132220404-3a388d11-072e-49e8-8161-bff149c07852.gif)

Titlebar works pretty well now and the new menubar isn't half bad. I'm still working on making rounded corners that look OK.

Module and example available here:
https://github.com/PicoPlanetDev/Sun-Valley-titlebar
