### ISSUE TITLE
How to Change TButton Colors

### ISSUE THREAD

**Issue by yuvarajvelumani** [rdbende/Sun-Valley-ttk-examples#2]

**Comment by rdbende** [comment]
Unfortunately it's not possible to change the button color dynamically, but you can use the `Accent.TButton` style to make it highlighted.
https://github.com/rdbende/Sun-Valley-ttk-examples/blob/a19631e21b58ede512f561f5e48f3f3e5ec874e1/Simple%20example/example.py#L144-L147
